// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/callsign_qth_record.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> addCallsignQthRecord(
        {required String callsign, required String qth}) =>
    RustLib.instance.api
        .crateApiCallsignQthAddCallsignQthRecord(callsign: callsign, qth: qth);

Future<List<CallsignQthRecord>> getCallsignQthHistory(
        {required String callsign, PlatformInt64? limit}) =>
    RustLib.instance.api.crateApiCallsignQthGetCallsignQthHistory(
        callsign: callsign, limit: limit);

Future<String?> getLastRecordedTime(
        {required String callsign, required String qth}) =>
    RustLib.instance.api
        .crateApiCallsignQthGetLastRecordedTime(callsign: callsign, qth: qth);

Future<void> clearCallsignQthHistory() =>
    RustLib.instance.api.crateApiCallsignQthClearCallsignQthHistory();
