// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getOrCreateDeviceId() =>
    RustLib.instance.api.crateApiCollaborationGetOrCreateDeviceId();

Future<String?> getCollaborationBinding(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationGetCollaborationBinding(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId);

Future<String?> getSessionCollaborationBinding({required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationGetSessionCollaborationBinding(
        sessionId: sessionId);

Future<String> getPublishSnapshot({required String sessionId}) =>
    RustLib.instance.api
        .crateApiCollaborationGetPublishSnapshot(sessionId: sessionId);

Future<String> beginPublishSnapshot(
        {required String serverInstanceId,
        required String serverOrigin,
        required String accountId,
        required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationBeginPublishSnapshot(
        serverInstanceId: serverInstanceId,
        serverOrigin: serverOrigin,
        accountId: accountId,
        sessionId: sessionId);

Future<void> abortPublish(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationAbortPublish(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId);

Future<String> installCollaborationSnapshot({required String requestJson}) =>
    RustLib.instance.api.crateApiCollaborationInstallCollaborationSnapshot(
        requestJson: requestJson);

Future<void> markCollaborationRevoked(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationMarkCollaborationRevoked(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId);

Future<String> updateCollaborationMembership(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        required String membershipId,
        required PlatformInt64 membershipVersion,
        required String role}) =>
    RustLib.instance.api.crateApiCollaborationUpdateCollaborationMembership(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        membershipId: membershipId,
        membershipVersion: membershipVersion,
        role: role);

Future<String> listPendingCollaborationMutations(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        PlatformInt64? limit}) =>
    RustLib.instance.api.crateApiCollaborationListPendingCollaborationMutations(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        limit: limit);

Future<void> markCollaborationMutationsSending(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        required String mutationIdsJson}) =>
    RustLib.instance.api.crateApiCollaborationMarkCollaborationMutationsSending(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        mutationIdsJson: mutationIdsJson);

Future<void> markCollaborationMutationAccepted(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        required String mutationId,
        required PlatformInt64 acceptedEventSeq}) =>
    RustLib.instance.api.crateApiCollaborationMarkCollaborationMutationAccepted(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        mutationId: mutationId,
        acceptedEventSeq: acceptedEventSeq);

Future<void> markCollaborationMutationRetry({required String requestJson}) =>
    RustLib.instance.api.crateApiCollaborationMarkCollaborationMutationRetry(
        requestJson: requestJson);

Future<void> markCollaborationMutationRejected(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        required String mutationId,
        required String errorCode,
        required String errorMessage,
        String? detailsJson}) =>
    RustLib.instance.api.crateApiCollaborationMarkCollaborationMutationRejected(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        mutationId: mutationId,
        errorCode: errorCode,
        errorMessage: errorMessage,
        detailsJson: detailsJson);

Future<String> recordCollaborationMutationConflict(
        {required String requestJson}) =>
    RustLib.instance.api
        .crateApiCollaborationRecordCollaborationMutationConflict(
            requestJson: requestJson);

Future<String> applyCollaborationEvent({required String requestJson}) =>
    RustLib.instance.api
        .crateApiCollaborationApplyCollaborationEvent(requestJson: requestJson);

Future<void> setCollaborationHeadSeq(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId,
        required PlatformInt64 headSeq}) =>
    RustLib.instance.api.crateApiCollaborationSetCollaborationHeadSeq(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId,
        headSeq: headSeq);

Future<String> getCollaborationSyncStatus(
        {required String serverInstanceId,
        required String accountId,
        required String sessionId}) =>
    RustLib.instance.api.crateApiCollaborationGetCollaborationSyncStatus(
        serverInstanceId: serverInstanceId,
        accountId: accountId,
        sessionId: sessionId);
