// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bind_value`, `insert_from_json`, `query_table`, `row_to_json`

Future<String> getDatabaseStatus() =>
    RustLib.instance.api.crateApiDatabaseGetDatabaseStatus();

Future<String> exportDatabase() =>
    RustLib.instance.api.crateApiDatabaseExportDatabase();

Future<void> importDatabase({required String jsonData}) =>
    RustLib.instance.api.crateApiDatabaseImportDatabase(jsonData: jsonData);

Future<void> clearAllData() =>
    RustLib.instance.api.crateApiDatabaseClearAllData();
