// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `allowed_columns`, `backup_tables`, `bind_value`, `clear_database_tables`, `ensure_dictionary_types`, `ensure_json_column_type`, `ensure_log_time_column`, `ensure_nonblank_identifier`, `ensure_nonblank_required_value`, `ensure_rfc3339_column`, `ensure_sqlite_column_type`, `export_column_decode_error`, `insert_from_json`, `is_valid_log_time`, `json_any_columns`, `json_array_columns`, `json_object_columns`, `optional_identifier_columns`, `optional_integer_columns`, `optional_rfc3339_columns`, `optional_text_columns`, `query_table`, `required_identifier_columns`, `required_integer_columns`, `required_rfc3339_columns`, `required_text_columns`, `required_value_columns`, `row_to_json`, `validate_backup`, `validate_restored_database`

Future<String> getDatabaseStatus() =>
    RustLib.instance.api.crateApiDatabaseGetDatabaseStatus();

Future<String> exportDatabase() =>
    RustLib.instance.api.crateApiDatabaseExportDatabase();

Future<void> importDatabase({required String jsonData}) =>
    RustLib.instance.api.crateApiDatabaseImportDatabase(jsonData: jsonData);

Future<void> clearAllData() =>
    RustLib.instance.api.crateApiDatabaseClearAllData();
