// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/dict_item.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_dictionary_rows`, `aggregate_log_values`, `dictionary_state_token`, `dictionary_values`, `ensure_active`, `ensure_inactive`, `tombstone`, `upsert_ai_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BulkUpsertDictItem`, `BulkUpsertDictRequest`, `DictionaryAiApplyRequest`, `DictionaryAiOperation`, `DictionaryAiSource`

Future<List<DictItem>> searchDict(
        {required String dictType,
        required String query,
        PlatformInt64? limit}) =>
    RustLib.instance.api.crateApiDictionariesSearchDict(
        dictType: dictType, query: query, limit: limit);

Future<void> addDictItem({required String dictType, required String raw}) =>
    RustLib.instance.api
        .crateApiDictionariesAddDictItem(dictType: dictType, raw: raw);

Future<void> upsertDictItem(
        {required String dictType,
        required String raw,
        String? pinyin,
        String? abbreviation}) =>
    RustLib.instance.api.crateApiDictionariesUpsertDictItem(
        dictType: dictType,
        raw: raw,
        pinyin: pinyin,
        abbreviation: abbreviation);

Future<void> upsertDictItemIfActive(
        {required String dictType,
        required String raw,
        String? pinyin,
        String? abbreviation}) =>
    RustLib.instance.api.crateApiDictionariesUpsertDictItemIfActive(
        dictType: dictType,
        raw: raw,
        pinyin: pinyin,
        abbreviation: abbreviation);

Future<DictItem> renameDictItem(
        {required String dictType,
        required String oldRaw,
        required String newRaw,
        String? pinyin,
        String? abbreviation}) =>
    RustLib.instance.api.crateApiDictionariesRenameDictItem(
        dictType: dictType,
        oldRaw: oldRaw,
        newRaw: newRaw,
        pinyin: pinyin,
        abbreviation: abbreviation);

/// Atomically imports user-supplied dictionary entries.
///
/// Unlike built-in dictionary synchronization, an explicit import revives an
/// existing tombstoned `(dict_type, raw)` row. The whole request is committed
/// in one SQLite transaction, so a failure cannot leave a partially imported
/// file behind.
Future<void> bulkUpsertDictItems({required String requestJson}) =>
    RustLib.instance.api
        .crateApiDictionariesBulkUpsertDictItems(requestJson: requestJson);

/// Returns an aggregate-only data source for the on-device dictionary
/// assistant. No session IDs, timestamps, remarks, or complete log rows leave
/// SQLite. Collaboration and local sessions are intentionally both included.
Future<String> getDictionaryAiSource() =>
    RustLib.instance.api.crateApiDictionariesGetDictionaryAiSource();

/// Applies a reviewed assistant plan in one immediate SQLite transaction.
/// The state token prevents suggestions generated for an older dictionary
/// snapshot from changing newer user edits.
Future<String> applyDictionaryAiChanges({required String requestJson}) =>
    RustLib.instance.api
        .crateApiDictionariesApplyDictionaryAiChanges(requestJson: requestJson);

Future<List<DictItem>> getDictItems({required String dictType}) =>
    RustLib.instance.api.crateApiDictionariesGetDictItems(dictType: dictType);

Future<DictItem?> getDictItemByRaw(
        {required String dictType, required String raw}) =>
    RustLib.instance.api
        .crateApiDictionariesGetDictItemByRaw(dictType: dictType, raw: raw);

Future<bool> softDeleteDictItem(
        {required String dictType, required String raw}) =>
    RustLib.instance.api
        .crateApiDictionariesSoftDeleteDictItem(dictType: dictType, raw: raw);

Future<void> softDeleteDictItems({required String dictType}) =>
    RustLib.instance.api
        .crateApiDictionariesSoftDeleteDictItems(dictType: dictType);

Future<void> resetDictionaries() =>
    RustLib.instance.api.crateApiDictionariesResetDictionaries();

Future<BigInt> seedDict(
        {required String dictType, required List<String> items}) =>
    RustLib.instance.api
        .crateApiDictionariesSeedDict(dictType: dictType, items: items);
