// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/dict_item.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<DictItem>> searchDict(
        {required String dictType,
        required String query,
        PlatformInt64? limit}) =>
    RustLib.instance.api.crateApiDictionariesSearchDict(
        dictType: dictType, query: query, limit: limit);

Future<void> addDictItem({required String dictType, required String raw}) =>
    RustLib.instance.api
        .crateApiDictionariesAddDictItem(dictType: dictType, raw: raw);

Future<BigInt> seedDict(
        {required String dictType, required List<String> items}) =>
    RustLib.instance.api
        .crateApiDictionariesSeedDict(dictType: dictType, items: items);
