// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/log_entry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LogEntry> addLog(
        {required String sessionId,
        required String controller,
        required String callsign,
        String? rstSent,
        String? rstRcvd,
        String? qth,
        String? device,
        String? power,
        String? antenna,
        String? height}) =>
    RustLib.instance.api.crateApiLogsAddLog(
        sessionId: sessionId,
        controller: controller,
        callsign: callsign,
        rstSent: rstSent,
        rstRcvd: rstRcvd,
        qth: qth,
        device: device,
        power: power,
        antenna: antenna,
        height: height);

Future<List<LogEntry>> getLogs(
        {required String sessionId,
        PlatformInt64? page,
        PlatformInt64? pageSize,
        String? search}) =>
    RustLib.instance.api.crateApiLogsGetLogs(
        sessionId: sessionId, page: page, pageSize: pageSize, search: search);

Future<LogStats> getLogStats({required String sessionId}) =>
    RustLib.instance.api.crateApiLogsGetLogStats(sessionId: sessionId);

Future<List<LogEntry>> getRecentByCallsign(
        {required String callsign, PlatformInt64? limit}) =>
    RustLib.instance.api
        .crateApiLogsGetRecentByCallsign(callsign: callsign, limit: limit);

Future<void> deleteLog({required String syncId}) =>
    RustLib.instance.api.crateApiLogsDeleteLog(syncId: syncId);

Future<void> undoLastLog({required String sessionId}) =>
    RustLib.instance.api.crateApiLogsUndoLastLog(sessionId: sessionId);
