// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_dataset`, `validate_hash`

/// Returns device-local pairing state and the requested account baseline.
Future<String> loadPersonalCloudState(
        {required String scopeHash, required String dataset}) =>
    RustLib.instance.api.crateApiPersonalCloudLoadPersonalCloudState(
        scopeHash: scopeHash, dataset: dataset);

/// Atomically stores an accepted baseline. Snapshot JSON is local-only and is
/// deliberately excluded from normal database backup/export.
Future<void> savePersonalCloudBaseline(
        {required String scopeHash,
        required String dataset,
        required PlatformInt64 remoteRevision,
        required String snapshotJson,
        required String checksum,
        required bool claimOwner,
        required bool clearPairingRequirement}) =>
    RustLib.instance.api.crateApiPersonalCloudSavePersonalCloudBaseline(
        scopeHash: scopeHash,
        dataset: dataset,
        remoteRevision: remoteRevision,
        snapshotJson: snapshotJson,
        checksum: checksum,
        claimOwner: claimOwner,
        clearPairingRequirement: clearPairingRequirement);

Future<void> requirePersonalCloudPairing({required String reason}) =>
    RustLib.instance.api
        .crateApiPersonalCloudRequirePersonalCloudPairing(reason: reason);
