// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assert_personal_records_unchanged`, `clear_personal_records`, `import_personal_records`, `is_strict_rfc3339`, `is_valid_log_time`, `parse_snapshot`, `reject_collaboration_identity_collisions`, `upsert_personal_logs`, `upsert_personal_sessions`, `validate_optional_rfc3339`, `validate_optional_string_length`, `validate_rfc3339`, `validate_rows_shape`, `validate_snapshot`, `validate_stable_id`, `validate_string_length`, `validate_wire_shape`, `verify_installed_snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ImportMode`, `PersonalLogRow`, `PersonalRecordsSnapshot`, `PersonalSessionRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from_row`, `from_row`

/// Exports only sessions that have no collaboration binding on this
/// installation, together with all of their logs (including tombstones).
///
/// The wire rows mirror the v6 database backup's snake_case session/log
/// metadata, except for installation-local sessions.share_code and logs.id.
Future<String> exportPersonalRecords() =>
    RustLib.instance.api.crateApiPersonalRecordsExportPersonalRecords();

/// Atomically replaces all local-only sessions and logs with a personal cloud
/// snapshot. Collaboration replicas and every other table remain untouched.
Future<String> replacePersonalRecords({required String jsonData}) =>
    RustLib.instance.api
        .crateApiPersonalRecordsReplacePersonalRecords(jsonData: jsonData);

/// Atomically replaces personal records only when their current durable rows
/// still match the snapshot observed before a cloud download. The comparison
/// and replacement share one `BEGIN IMMEDIATE` transaction, so a local save
/// cannot slip between the guard and the destructive clear.
Future<String> replacePersonalRecordsIfUnchanged(
        {required String jsonData, required String expectedLocalJsonData}) =>
    RustLib.instance.api
        .crateApiPersonalRecordsReplacePersonalRecordsIfUnchanged(
            jsonData: jsonData, expectedLocalJsonData: expectedLocalJsonData);

/// Atomically merges a personal cloud snapshot by stable session/log identity.
/// Existing local-only records absent from the snapshot remain available.
Future<String> mergePersonalRecords({required String jsonData}) =>
    RustLib.instance.api
        .crateApiPersonalRecordsMergePersonalRecords(jsonData: jsonData);
