// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `database_type`, `export_in_transaction`, `parse_snapshot`, `validate_snapshot`, `wire_type`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DictionaryOverride`, `PersonalDictionarySnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

Future<String> exportPersonalDictionary() =>
    RustLib.instance.api.crateApiPersonalDictionaryExportPersonalDictionary();

Future<String> replacePersonalDictionaryIfUnchanged(
        {required String jsonData, required String expectedLocalJsonData}) =>
    RustLib.instance.api
        .crateApiPersonalDictionaryReplacePersonalDictionaryIfUnchanged(
            jsonData: jsonData, expectedLocalJsonData: expectedLocalJsonData);
