// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from_row`

Future<Session> createSession({required String title}) =>
    RustLib.instance.api.crateApiSessionsCreateSession(title: title);

Future<List<Session>> listSessions() =>
    RustLib.instance.api.crateApiSessionsListSessions();

Future<void> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiSessionsCloseSession(sessionId: sessionId);

Future<Session> joinSession({required String shareCode}) =>
    RustLib.instance.api.crateApiSessionsJoinSession(shareCode: shareCode);
