// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `close_session_locally_from_pool`, `convert_collaboration_session_to_local_from_pool`, `copy_collaboration_session_to_local_from_pool`, `hard_delete_session_from_pool`, `into_session`, `into_summary`, `list_session_summaries_from_pool`, `reopen_local_session_from_pool`, `replace_collaboration_session_locally_from_pool`, `replace_collaboration_session_locally_in_tx`, `start_local_session_from_pool`, `stop_collaboration_session_locally_from_pool`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LocalCopyLogRow`, `LocalReplacementStatus`, `SessionRow`, `SessionSummaryRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from_row`, `from_row`, `from_row`

Future<Session> createSession({required String title}) =>
    RustLib.instance.api.crateApiSessionsCreateSession(title: title);

/// Starts a new writable local session atomically.
///
/// Any currently active local-only session is closed in the same transaction
/// that inserts the replacement. Collaboration replicas stay untouched, so a
/// recorder can leave an on-device shared-session cache available while
/// starting an independent local net. If insertion fails, the transaction
/// rolls back the close as well.
Future<Session> startLocalSession({required String title}) =>
    RustLib.instance.api.crateApiSessionsStartLocalSession(title: title);

Future<List<Session>> listSessions() =>
    RustLib.instance.api.crateApiSessionsListSessions();

Future<List<SessionSummary>> listSessionSummaries() =>
    RustLib.instance.api.crateApiSessionsListSessionSummaries();

Future<void> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiSessionsCloseSession(sessionId: sessionId);

/// Reopens a closed, local-only session on this device.
///
/// Collaboration sessions must be reopened through the synchronized
/// collaboration API. To keep the local recorder unambiguous, any other
/// active local-only session is closed in the same transaction.
Future<Session> reopenLocalSession({required String sessionId}) =>
    RustLib.instance.api
        .crateApiSessionsReopenLocalSession(sessionId: sessionId);

/// Creates an independent, writable local copy of a collaboration session.
///
/// The source Session, collaboration binding, synchronization queue, conflicts,
/// cached live draft, and offline records are intentionally left untouched.
/// Only materialized, non-deleted logs are copied, each with a new sync id so a
/// later rejoin cannot confuse the local fork with canonical server entities.
Future<Session> copyCollaborationSessionToLocal(
        {required String sessionId, required String title}) =>
    RustLib.instance.api.crateApiSessionsCopyCollaborationSessionToLocal(
        sessionId: sessionId, title: title);

/// Replaces a synchronized collaboration session with an independent,
/// writable local session without contacting the collaboration server.
///
/// The replacement receives new session and log identifiers. Once the local
/// replacement is durable, the source session and all of its local replica
/// metadata are removed in the same transaction.
Future<Session> convertCollaborationSessionToLocal(
        {required String sessionId}) =>
    RustLib.instance.api.crateApiSessionsConvertCollaborationSessionToLocal(
        sessionId: sessionId);

/// Stops synchronization for one collaboration replica on this device.
///
/// The currently materialized, non-deleted logs are preserved in an
/// independent local session with new identifiers. All replica-only state,
/// including pending mutations, conflicts, cached live drafts, and offline
/// records, is discarded. No request or mutation is sent to the server.
Future<Session> stopCollaborationSessionLocally({required String sessionId}) =>
    RustLib.instance.api
        .crateApiSessionsStopCollaborationSessionLocally(sessionId: sessionId);

/// Closes a session only on this device and returns its canonical local row.
///
/// A local-only session keeps its identifier. A collaboration replica is
/// replaced by a closed local-only session with new session and log identifiers
/// so the server session, membership, and other devices remain untouched.
Future<Session> closeSessionLocally({required String sessionId}) =>
    RustLib.instance.api
        .crateApiSessionsCloseSessionLocally(sessionId: sessionId);

/// Permanently removes a session from this device.
///
/// This is deliberately a local-only operation. Deleting the collaboration
/// binding also cascades through every local replica table, but no mutation is
/// sent to the server and the shared server session is left untouched. Callers
/// that keep a selected-session pointer must clear it before or immediately
/// after deleting that selected row.
Future<void> hardDeleteSession({required String sessionId}) =>
    RustLib.instance.api
        .crateApiSessionsHardDeleteSession(sessionId: sessionId);

Future<Session> joinSession({required String shareCode}) =>
    RustLib.instance.api.crateApiSessionsJoinSession(shareCode: shareCode);

Future<void> updateCollaborationSessionTitle(
        {required String sessionId, required String title}) =>
    RustLib.instance.api.crateApiSessionsUpdateCollaborationSessionTitle(
        sessionId: sessionId, title: title);

Future<void> reopenCollaborationSession({required String sessionId}) =>
    RustLib.instance.api
        .crateApiSessionsReopenCollaborationSession(sessionId: sessionId);
