// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiSettingsGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSettingsSetSetting(key: key, value: value);

Future<List<(String, String)>> getAllSettings() =>
    RustLib.instance.api.crateApiSettingsGetAllSettings();
