// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/dictionaries.dart';
import 'api/export.dart';
import 'api/logs.dart';
import 'api/sessions.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/dict_item.dart';
import 'models/log_entry.dart';
import 'models/session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 463587873;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'openlogtool_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDictionariesAddDictItem(
      {required String dictType, required String raw});

  Future<LogEntry> crateApiLogsAddLog(
      {required String sessionId,
      required String controller,
      required String callsign,
      String? rstSent,
      String? rstRcvd,
      String? qth,
      String? device,
      String? power,
      String? antenna,
      String? height});

  Future<void> crateApiSessionsCloseSession({required String sessionId});

  Future<Session> crateApiSessionsCreateSession({required String title});

  Future<void> crateApiLogsDeleteLog({required String syncId});

  Future<Uint8List> crateApiExportExportExcel({required String sessionId});

  Future<Uint8List> crateApiExportExportJson({required String sessionId});

  Future<List<(String, String)>> crateApiSettingsGetAllSettings();

  Future<DictItem?> crateApiDictionariesGetDictItemByRaw(
      {required String dictType, required String raw});

  Future<List<DictItem>> crateApiDictionariesGetDictItems(
      {required String dictType});

  Future<LogStats> crateApiLogsGetLogStats({required String sessionId});

  Future<List<LogEntry>> crateApiLogsGetLogs(
      {required String sessionId,
      PlatformInt64? page,
      PlatformInt64? pageSize,
      String? search});

  Future<List<LogEntry>> crateApiLogsGetRecentByCallsign(
      {required String callsign, PlatformInt64? limit});

  Future<String?> crateApiSettingsGetSetting({required String key});

  Future<void> crateApiInitDatabase({required String dbPath});

  Future<Session> crateApiSessionsJoinSession({required String shareCode});

  Future<List<Session>> crateApiSessionsListSessions();

  Future<void> crateApiDictionariesResetDictionaries();

  Future<List<DictItem>> crateApiDictionariesSearchDict(
      {required String dictType, required String query, PlatformInt64? limit});

  Future<BigInt> crateApiDictionariesSeedDict(
      {required String dictType, required List<String> items});

  Future<void> crateApiSettingsSetSetting(
      {required String key, required String value});

  Future<void> crateApiDictionariesSoftDeleteDictItems(
      {required String dictType});

  Future<void> crateApiLogsUndoLastLog({required String sessionId});

  Future<LogEntry> crateApiLogsUpdateLog(
      {required String syncId,
      required String controller,
      required String callsign,
      String? rstSent,
      String? rstRcvd,
      String? qth,
      String? device,
      String? power,
      String? antenna,
      String? height});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDictionariesAddDictItem(
      {required String dictType, required String raw}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        sse_encode_String(raw, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesAddDictItemConstMeta,
      argValues: [dictType, raw],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesAddDictItemConstMeta =>
      const TaskConstMeta(
        debugName: "add_dict_item",
        argNames: ["dictType", "raw"],
      );

  @override
  Future<LogEntry> crateApiLogsAddLog(
      {required String sessionId,
      required String controller,
      required String callsign,
      String? rstSent,
      String? rstRcvd,
      String? qth,
      String? device,
      String? power,
      String? antenna,
      String? height}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_String(controller, serializer);
        sse_encode_String(callsign, serializer);
        sse_encode_opt_String(rstSent, serializer);
        sse_encode_opt_String(rstRcvd, serializer);
        sse_encode_opt_String(qth, serializer);
        sse_encode_opt_String(device, serializer);
        sse_encode_opt_String(power, serializer);
        sse_encode_opt_String(antenna, serializer);
        sse_encode_opt_String(height, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_log_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsAddLogConstMeta,
      argValues: [
        sessionId,
        controller,
        callsign,
        rstSent,
        rstRcvd,
        qth,
        device,
        power,
        antenna,
        height
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsAddLogConstMeta => const TaskConstMeta(
        debugName: "add_log",
        argNames: [
          "sessionId",
          "controller",
          "callsign",
          "rstSent",
          "rstRcvd",
          "qth",
          "device",
          "power",
          "antenna",
          "height"
        ],
      );

  @override
  Future<void> crateApiSessionsCloseSession({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionsCloseSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionsCloseSessionConstMeta =>
      const TaskConstMeta(
        debugName: "close_session",
        argNames: ["sessionId"],
      );

  @override
  Future<Session> crateApiSessionsCreateSession({required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_session,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionsCreateSessionConstMeta,
      argValues: [title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionsCreateSessionConstMeta =>
      const TaskConstMeta(
        debugName: "create_session",
        argNames: ["title"],
      );

  @override
  Future<void> crateApiLogsDeleteLog({required String syncId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(syncId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsDeleteLogConstMeta,
      argValues: [syncId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsDeleteLogConstMeta => const TaskConstMeta(
        debugName: "delete_log",
        argNames: ["syncId"],
      );

  @override
  Future<Uint8List> crateApiExportExportExcel({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportExportExcelConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportExportExcelConstMeta => const TaskConstMeta(
        debugName: "export_excel",
        argNames: ["sessionId"],
      );

  @override
  Future<Uint8List> crateApiExportExportJson({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportExportJsonConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportExportJsonConstMeta => const TaskConstMeta(
        debugName: "export_json",
        argNames: ["sessionId"],
      );

  @override
  Future<List<(String, String)>> crateApiSettingsGetAllSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_record_string_string,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSettingsGetAllSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsGetAllSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_settings",
        argNames: [],
      );

  @override
  Future<DictItem?> crateApiDictionariesGetDictItemByRaw(
      {required String dictType, required String raw}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        sse_encode_String(raw, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_dict_item,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesGetDictItemByRawConstMeta,
      argValues: [dictType, raw],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesGetDictItemByRawConstMeta =>
      const TaskConstMeta(
        debugName: "get_dict_item_by_raw",
        argNames: ["dictType", "raw"],
      );

  @override
  Future<List<DictItem>> crateApiDictionariesGetDictItems(
      {required String dictType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dict_item,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesGetDictItemsConstMeta,
      argValues: [dictType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesGetDictItemsConstMeta =>
      const TaskConstMeta(
        debugName: "get_dict_items",
        argNames: ["dictType"],
      );

  @override
  Future<LogStats> crateApiLogsGetLogStats({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_log_stats,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsGetLogStatsConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsGetLogStatsConstMeta => const TaskConstMeta(
        debugName: "get_log_stats",
        argNames: ["sessionId"],
      );

  @override
  Future<List<LogEntry>> crateApiLogsGetLogs(
      {required String sessionId,
      PlatformInt64? page,
      PlatformInt64? pageSize,
      String? search}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_opt_box_autoadd_i_64(page, serializer);
        sse_encode_opt_box_autoadd_i_64(pageSize, serializer);
        sse_encode_opt_String(search, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_log_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsGetLogsConstMeta,
      argValues: [sessionId, page, pageSize, search],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsGetLogsConstMeta => const TaskConstMeta(
        debugName: "get_logs",
        argNames: ["sessionId", "page", "pageSize", "search"],
      );

  @override
  Future<List<LogEntry>> crateApiLogsGetRecentByCallsign(
      {required String callsign, PlatformInt64? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(callsign, serializer);
        sse_encode_opt_box_autoadd_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_log_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsGetRecentByCallsignConstMeta,
      argValues: [callsign, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsGetRecentByCallsignConstMeta =>
      const TaskConstMeta(
        debugName: "get_recent_by_callsign",
        argNames: ["callsign", "limit"],
      );

  @override
  Future<String?> crateApiSettingsGetSetting({required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSettingsGetSettingConstMeta,
      argValues: [key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsGetSettingConstMeta => const TaskConstMeta(
        debugName: "get_setting",
        argNames: ["key"],
      );

  @override
  Future<void> crateApiInitDatabase({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitDatabaseConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta => const TaskConstMeta(
        debugName: "init_database",
        argNames: ["dbPath"],
      );

  @override
  Future<Session> crateApiSessionsJoinSession({required String shareCode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(shareCode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_session,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionsJoinSessionConstMeta,
      argValues: [shareCode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionsJoinSessionConstMeta =>
      const TaskConstMeta(
        debugName: "join_session",
        argNames: ["shareCode"],
      );

  @override
  Future<List<Session>> crateApiSessionsListSessions() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_session,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSessionsListSessionsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSessionsListSessionsConstMeta =>
      const TaskConstMeta(
        debugName: "list_sessions",
        argNames: [],
      );

  @override
  Future<void> crateApiDictionariesResetDictionaries() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesResetDictionariesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesResetDictionariesConstMeta =>
      const TaskConstMeta(
        debugName: "reset_dictionaries",
        argNames: [],
      );

  @override
  Future<List<DictItem>> crateApiDictionariesSearchDict(
      {required String dictType, required String query, PlatformInt64? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        sse_encode_String(query, serializer);
        sse_encode_opt_box_autoadd_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dict_item,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesSearchDictConstMeta,
      argValues: [dictType, query, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesSearchDictConstMeta =>
      const TaskConstMeta(
        debugName: "search_dict",
        argNames: ["dictType", "query", "limit"],
      );

  @override
  Future<BigInt> crateApiDictionariesSeedDict(
      {required String dictType, required List<String> items}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        sse_encode_list_String(items, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesSeedDictConstMeta,
      argValues: [dictType, items],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesSeedDictConstMeta =>
      const TaskConstMeta(
        debugName: "seed_dict",
        argNames: ["dictType", "items"],
      );

  @override
  Future<void> crateApiSettingsSetSetting(
      {required String key, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSettingsSetSettingConstMeta,
      argValues: [key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsSetSettingConstMeta => const TaskConstMeta(
        debugName: "set_setting",
        argNames: ["key", "value"],
      );

  @override
  Future<void> crateApiDictionariesSoftDeleteDictItems(
      {required String dictType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dictType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDictionariesSoftDeleteDictItemsConstMeta,
      argValues: [dictType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionariesSoftDeleteDictItemsConstMeta =>
      const TaskConstMeta(
        debugName: "soft_delete_dict_items",
        argNames: ["dictType"],
      );

  @override
  Future<void> crateApiLogsUndoLastLog({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsUndoLastLogConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsUndoLastLogConstMeta => const TaskConstMeta(
        debugName: "undo_last_log",
        argNames: ["sessionId"],
      );

  @override
  Future<LogEntry> crateApiLogsUpdateLog(
      {required String syncId,
      required String controller,
      required String callsign,
      String? rstSent,
      String? rstRcvd,
      String? qth,
      String? device,
      String? power,
      String? antenna,
      String? height}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(syncId, serializer);
        sse_encode_String(controller, serializer);
        sse_encode_String(callsign, serializer);
        sse_encode_opt_String(rstSent, serializer);
        sse_encode_opt_String(rstRcvd, serializer);
        sse_encode_opt_String(qth, serializer);
        sse_encode_opt_String(device, serializer);
        sse_encode_opt_String(power, serializer);
        sse_encode_opt_String(antenna, serializer);
        sse_encode_opt_String(height, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_log_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLogsUpdateLogConstMeta,
      argValues: [
        syncId,
        controller,
        callsign,
        rstSent,
        rstRcvd,
        qth,
        device,
        power,
        antenna,
        height
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLogsUpdateLogConstMeta => const TaskConstMeta(
        debugName: "update_log",
        argNames: [
          "syncId",
          "controller",
          "callsign",
          "rstSent",
          "rstRcvd",
          "qth",
          "device",
          "power",
          "antenna",
          "height"
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  DictItem dco_decode_box_autoadd_dict_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dict_item(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  DictItem dco_decode_dict_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DictItem(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      dictType: dco_decode_String(arr[1]),
      raw: dco_decode_String(arr[2]),
      pinyin: dco_decode_opt_String(arr[3]),
      abbreviation: dco_decode_opt_String(arr[4]),
      syncId: dco_decode_String(arr[5]),
      createdAt: dco_decode_String(arr[6]),
      updatedAt: dco_decode_String(arr[7]),
      deletedAt: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DictItem> dco_decode_list_dict_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dict_item).toList();
  }

  @protected
  List<LogEntry> dco_decode_list_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_log_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<Session> dco_decode_list_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session).toList();
  }

  @protected
  LogEntry dco_decode_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return LogEntry(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      syncId: dco_decode_String(arr[1]),
      sessionId: dco_decode_String(arr[2]),
      time: dco_decode_String(arr[3]),
      controller: dco_decode_String(arr[4]),
      callsign: dco_decode_String(arr[5]),
      rstSent: dco_decode_opt_String(arr[6]),
      rstRcvd: dco_decode_opt_String(arr[7]),
      qth: dco_decode_opt_String(arr[8]),
      device: dco_decode_opt_String(arr[9]),
      power: dco_decode_opt_String(arr[10]),
      antenna: dco_decode_opt_String(arr[11]),
      height: dco_decode_opt_String(arr[12]),
      createdAt: dco_decode_String(arr[13]),
      updatedAt: dco_decode_String(arr[14]),
      deletedAt: dco_decode_opt_String(arr[15]),
      sourceDeviceId: dco_decode_opt_String(arr[16]),
    );
  }

  @protected
  LogStats dco_decode_log_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LogStats(
      total: dco_decode_i_64(arr[0]),
      today: dco_decode_i_64(arr[1]),
      last7Days: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DictItem? dco_decode_opt_box_autoadd_dict_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dict_item(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  Session dco_decode_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return Session(
      sessionId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
      shareCode: dco_decode_opt_String(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      updatedAt: dco_decode_String(arr[5]),
      closedAt: dco_decode_opt_String(arr[6]),
      deletedAt: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  DictItem sse_decode_box_autoadd_dict_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dict_item(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  DictItem sse_decode_dict_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_dictType = sse_decode_String(deserializer);
    var var_raw = sse_decode_String(deserializer);
    var var_pinyin = sse_decode_opt_String(deserializer);
    var var_abbreviation = sse_decode_opt_String(deserializer);
    var var_syncId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_deletedAt = sse_decode_opt_String(deserializer);
    return DictItem(
        id: var_id,
        dictType: var_dictType,
        raw: var_raw,
        pinyin: var_pinyin,
        abbreviation: var_abbreviation,
        syncId: var_syncId,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        deletedAt: var_deletedAt);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DictItem> sse_decode_list_dict_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DictItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dict_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<LogEntry> sse_decode_list_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LogEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_log_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<Session> sse_decode_list_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Session>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session(deserializer));
    }
    return ans_;
  }

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_syncId = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_controller = sse_decode_String(deserializer);
    var var_callsign = sse_decode_String(deserializer);
    var var_rstSent = sse_decode_opt_String(deserializer);
    var var_rstRcvd = sse_decode_opt_String(deserializer);
    var var_qth = sse_decode_opt_String(deserializer);
    var var_device = sse_decode_opt_String(deserializer);
    var var_power = sse_decode_opt_String(deserializer);
    var var_antenna = sse_decode_opt_String(deserializer);
    var var_height = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_deletedAt = sse_decode_opt_String(deserializer);
    var var_sourceDeviceId = sse_decode_opt_String(deserializer);
    return LogEntry(
        id: var_id,
        syncId: var_syncId,
        sessionId: var_sessionId,
        time: var_time,
        controller: var_controller,
        callsign: var_callsign,
        rstSent: var_rstSent,
        rstRcvd: var_rstRcvd,
        qth: var_qth,
        device: var_device,
        power: var_power,
        antenna: var_antenna,
        height: var_height,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        deletedAt: var_deletedAt,
        sourceDeviceId: var_sourceDeviceId);
  }

  @protected
  LogStats sse_decode_log_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_64(deserializer);
    var var_today = sse_decode_i_64(deserializer);
    var var_last7Days = sse_decode_i_64(deserializer);
    return LogStats(
        total: var_total, today: var_today, last7Days: var_last7Days);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DictItem? sse_decode_opt_box_autoadd_dict_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dict_item(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  Session sse_decode_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_shareCode = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_closedAt = sse_decode_opt_String(deserializer);
    var var_deletedAt = sse_decode_opt_String(deserializer);
    return Session(
        sessionId: var_sessionId,
        title: var_title,
        status: var_status,
        shareCode: var_shareCode,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        closedAt: var_closedAt,
        deletedAt: var_deletedAt);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_dict_item(
      DictItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dict_item(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_dict_item(DictItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.dictType, serializer);
    sse_encode_String(self.raw, serializer);
    sse_encode_opt_String(self.pinyin, serializer);
    sse_encode_opt_String(self.abbreviation, serializer);
    sse_encode_String(self.syncId, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.deletedAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dict_item(
      List<DictItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dict_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_log_entry(
      List<LogEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_log_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_session(List<Session> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session(item, serializer);
    }
  }

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.syncId, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.controller, serializer);
    sse_encode_String(self.callsign, serializer);
    sse_encode_opt_String(self.rstSent, serializer);
    sse_encode_opt_String(self.rstRcvd, serializer);
    sse_encode_opt_String(self.qth, serializer);
    sse_encode_opt_String(self.device, serializer);
    sse_encode_opt_String(self.power, serializer);
    sse_encode_opt_String(self.antenna, serializer);
    sse_encode_opt_String(self.height, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.deletedAt, serializer);
    sse_encode_opt_String(self.sourceDeviceId, serializer);
  }

  @protected
  void sse_encode_log_stats(LogStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.total, serializer);
    sse_encode_i_64(self.today, serializer);
    sse_encode_i_64(self.last7Days, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dict_item(
      DictItem? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dict_item(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_session(Session self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.shareCode, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.closedAt, serializer);
    sse_encode_opt_String(self.deletedAt, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
