name: openlogtool
description: OpenLogTool
publish_to: 'none'
version: 0.8.2+1
license: AGPL-3.0
homepage: https://github.com/Mazha0309/OpenLogTool
repository: https://github.com/Mazha0309/OpenLogTool.git
issue_tracker: https://github.com/Mazha0309/OpenLogTool/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  excel: ^4.0.6
  provider: ^6.1.1
  flutter_svg: ^2.0.10
  intl: ^0.20.2
  open_file: ^3.3.3
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.0
  http: ^1.2.0
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.8

flutter:
  assets:
    - icon.png
    - assets/dictionaries/
    - assets/fonts/
  fonts:
    - family: SarasaGothicSC
      fonts:
        - asset: assets/fonts/SarasaGothicSC-Regular.ttf
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon.png"
  ios: false
  remove_alpha_ios: true
  web: {}
