name: openlogtool
description: OpenLogTool
publish_to: 'none'
version: 2.9.3-R
license: AGPL-3.0
homepage: https://github.com/Mazha0309/OpenLogTool
repository: https://github.com/Mazha0309/OpenLogTool.git
issue_tracker: https://github.com/Mazha0309/OpenLogTool/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.3.1
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  excel: ^4.0.6
  provider: ^6.1.1
  intl: ^0.20.2
  path: ^1.9.0
  pub_semver: ^2.2.0
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  flutter_rust_bridge: 2.12.0
  lpinyin: ^2.0.3
  window_manager: ^0.5.2
  url_launcher: ^6.3.2
  record: ^6.1.2
  web: ^1.1.1
  idb_shim: ^2.9.6+2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.8

flutter:
  generate: true
  assets:
    - assets/images/app_icon_512.png
    - assets/dictionaries/
    - assets/fonts/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon.png"
  ios: false
  remove_alpha_ios: true
  web: {}
