import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:openlogtool/database/database_helper.dart';
import 'package:openlogtool/models/session.dart';
import 'package:openlogtool/services/instance_service.dart';

class SessionProvider with ChangeNotifier {
  static const _key = 'current_session_id';

  String? _currentSessionId;
  Session? _currentSession;

  String? get currentSessionId => _currentSessionId;
  Session? get currentSession => _currentSession;

  SessionProvider() {
    _init();
  }

  Future<void> _init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentSessionId = prefs.getString(_key);

    if (_currentSessionId != null) {
      final db = DatabaseHelper();
      final sessions = await db.getActiveSession();
      for (final session in sessions) {
        if (session['session_id']?.toString() == _currentSessionId) {
          _currentSession = Session.fromMap(session);
          break;
        }
      }
    }

    if (_currentSession == null) {
      await _ensureActiveSession();
    }
    notifyListeners();
  }

  Future<void> _ensureActiveSession() async {
    final db = DatabaseHelper();
    final activeSessions = await db.getActiveSession();
    if (activeSessions.isNotEmpty) {
      _currentSession = Session.fromMap(activeSessions.first);
      _currentSessionId = _currentSession!.sessionId;
    } else {
      await startNewSession(autoGenerated: true);
      return;
    }
    await _saveCurrentSessionId();
    notifyListeners();
  }

  Future<String> getOrCreateSessionId() async {
    if (_currentSessionId == null) {
      await _ensureActiveSession();
    }
    return _currentSessionId!;
  }

  Future<void> startNewSession(
      {String? title, bool autoGenerated = false}) async {
    final db = DatabaseHelper();

    if (_currentSessionId != null) {
      debugPrint('[Session] closing session: $_currentSessionId');
      await db.closeSession(_currentSessionId!);
    }

    final newSessionId = await Session.generateSessionId();
    final instanceId = await InstanceService.getInstanceId();
    final now = DateTime.now().toUtc();

    final defaultTitle = autoGenerated
        ? '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} ${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')} 记录'
        : (title ?? '新记录');

    final session = Session(
      sessionId: newSessionId,
      title: defaultTitle,
      status: 'active',
      createdAt: now.toIso8601String(),
      updatedAt: now.toIso8601String(),
      sourceDeviceId: instanceId,
    );

    debugPrint('[Session] inserting: ${session.toMap()}');
    await db.insertSession(session);
    _currentSessionId = newSessionId;
    _currentSession = session;
    await _saveCurrentSessionId();
    debugPrint('[Session] new session ready: $newSessionId');
    notifyListeners();
  }

  Future<void> _saveCurrentSessionId() async {
    final prefs = await SharedPreferences.getInstance();
    if (_currentSessionId != null) {
      await prefs.setString(_key, _currentSessionId!);
    }
  }
}
