import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:openlogtool/src/bridge/rust_api.dart';
import 'package:openlogtool/src/bridge/models/session.dart';

typedef LocalSessionReopener = Future<Session> Function(String sessionId);
typedef CollaborationSessionLocalCopier = Future<Session> Function(
  String sessionId,
  String title,
);
typedef CollaborationSessionLocalConverter = Future<Session> Function(
  String sessionId,
);
typedef CurrentSessionIdWriter = Future<bool> Function(String sessionId);

class SessionProvider with ChangeNotifier {
  static const _key = 'current_session_id';

  final LocalSessionReopener _localSessionReopener;
  final CollaborationSessionLocalCopier _collaborationSessionLocalCopier;
  final CollaborationSessionLocalConverter _collaborationSessionLocalConverter;
  final CurrentSessionIdWriter? _currentSessionIdWriter;
  bool _disposed = false;
  String? _currentSessionId;
  Session? _currentSession;
  Completer<void>? _initCompleter;

  String? get currentSessionId => _currentSessionId;
  Session? get currentSession => _currentSession;

  Future<void> get ready => _initCompleter?.future ?? Future.value();

  SessionProvider({
    LocalSessionReopener? localSessionReopener,
    CollaborationSessionLocalCopier? collaborationSessionLocalCopier,
    CollaborationSessionLocalConverter? collaborationSessionLocalConverter,
    CurrentSessionIdWriter? currentSessionIdWriter,
  })  : _localSessionReopener = localSessionReopener ??
            ((sessionId) => RustApi.reopenLocalSession(sessionId: sessionId)),
        _collaborationSessionLocalCopier = collaborationSessionLocalCopier ??
            ((sessionId, title) => RustApi.copyCollaborationSessionToLocal(
                  sessionId: sessionId,
                  title: title,
                )),
        _collaborationSessionLocalConverter =
            collaborationSessionLocalConverter ??
                ((sessionId) => RustApi.convertCollaborationSessionToLocal(
                      sessionId: sessionId,
                    )),
        _currentSessionIdWriter = currentSessionIdWriter {
    final completer = Completer<void>();
    _initCompleter = completer;
    scheduleMicrotask(() async {
      try {
        await _init();
      } catch (e, st) {
        debugPrint('[Session] init failed: $e\n$st');
      } finally {
        if (!completer.isCompleted) completer.complete();
      }
    });
  }

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  void _safeNotify() {
    if (_disposed) return;
    notifyListeners();
  }

  Future<void> _init() async {
    final prefs = await SharedPreferences.getInstance();
    final storedId = prefs.getString(_key);

    if (storedId != null && storedId.isNotEmpty) {
      try {
        final sessions = await RustApi.listSessions();
        final match = sessions
            .where((s) => s.sessionId == storedId && s.deletedAt == null)
            .toList();
        if (match.isNotEmpty) {
          _currentSession = match.first;
          _currentSessionId = match.first.sessionId;
        } else {
          debugPrint(
              '[Session] stored session $storedId no longer exists, clearing');
          await prefs.remove(_key);
        }
      } catch (_) {}
    }

    // Don't auto-create — wait for user to create via dialog
    _safeNotify();
  }

  Future<String> getOrCreateSessionId() async {
    await ready;
    if (_currentSessionId == null) {
      await _ensureActiveSession();
    }
    return _currentSessionId!;
  }

  Future<void> _ensureActiveSession() async {
    try {
      final sessions = await RustApi.listSessions();
      final active = sessions
          .where((s) => s.status == 'active' && s.deletedAt == null)
          .toList();
      if (active.isNotEmpty) {
        _currentSession = active.first;
        _currentSessionId = active.first.sessionId;
        await _saveCurrentSessionId();
        _safeNotify();
        return;
      }
    } catch (_) {}
  }

  Future<void> startNewSession(
      {String? title, bool autoGenerated = false}) async {
    try {
      final previousSessionId = _currentSessionId;
      if (previousSessionId != null) {
        final collaborationBinding =
            await RustApi.getSessionCollaborationBinding(
          sessionId: previousSessionId,
        );
        if (collaborationBinding == null) {
          debugPrint('[Session] closing session: $previousSessionId');
          await RustApi.closeSession(sessionId: previousSessionId);
        } else {
          debugPrint(
            '[Session] preserving read-only collaboration session: '
            '$previousSessionId',
          );
        }
      }

      final now = DateTime.now();
      final defaultTitle = autoGenerated
          ? '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} ${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')} 记录'
          : ((title?.trim().isNotEmpty ?? false) ? title!.trim() : '新记录');

      final session = await RustApi.createSession(title: defaultTitle);
      await _persistCurrentSessionId(session.sessionId);
      _currentSession = session;
      _currentSessionId = session.sessionId;
      debugPrint('[Session] new session ready: ${session.sessionId}');
      _safeNotify();
    } catch (e, st) {
      debugPrint('[Session] startNewSession ERROR: $e\n$st');
      rethrow;
    }
  }

  Future<List<Session>> listAvailableSessions() async {
    await ready;
    final sessions = await RustApi.listSessions();
    final available = sessions
        .where((session) => session.deletedAt == null)
        .toList(growable: false);
    return [...available]
      ..sort((left, right) => right.createdAt.compareTo(left.createdAt));
  }

  Future<void> switchToSession(String sessionId) async {
    final sessions = await listAvailableSessions();
    final match = sessions.where((s) => s.sessionId == sessionId).toList();
    if (match.isEmpty) {
      throw StateError('Session not found: $sessionId');
    }

    final nextSession = match.first;
    await _persistCurrentSessionId(nextSession.sessionId);
    _currentSession = nextSession;
    _currentSessionId = nextSession.sessionId;
    _safeNotify();
  }

  /// Reactivates and selects a closed local-only session.
  ///
  /// Rust atomically closes any other active local-only session and returns
  /// the new canonical local row, so this provider cannot keep presenting the
  /// previous session as writable after the operation succeeds.
  Future<void> reopenLocalSession(String sessionId) async {
    final reopened = await _localSessionReopener(sessionId);

    // The database transaction has already committed. Adopt its canonical
    // result before touching preferences so an I/O failure cannot leave the
    // in-memory provider pointing at a session Rust just closed.
    _currentSession = reopened;
    _currentSessionId = reopened.sessionId;
    _safeNotify();
    try {
      await _persistCurrentSessionId(reopened.sessionId);
    } catch (error, stackTrace) {
      // Persistence only controls which session is restored on next launch.
      // The committed database state remains authoritative for this process.
      debugPrint(
        '[Session] failed to persist reopened session selection: '
        '$error\n$stackTrace',
      );
    }
  }

  /// Creates and selects an independent local copy of the current
  /// collaboration session without contacting its server.
  Future<Session> copyCurrentCollaborationSessionToLocal({
    required String title,
  }) async {
    await ready;
    final sourceSessionId = _currentSessionId;
    if (sourceSessionId == null || _currentSession == null) {
      throw StateError('NO_CURRENT_SESSION');
    }
    final normalized = title.trim();
    if (normalized.isEmpty || normalized.runes.length > 200) {
      throw ArgumentError('会话标题长度应为 1–200 个字符');
    }

    final local = await _collaborationSessionLocalCopier(
      sourceSessionId,
      normalized,
    );
    if (_currentSessionId != sourceSessionId) {
      throw StateError('SESSION_CONTEXT_CHANGED');
    }
    if (local.sessionId == sourceSessionId || local.status != 'active') {
      throw StateError('LOCAL_SESSION_COPY_INVALID');
    }

    _currentSession = local;
    _currentSessionId = local.sessionId;
    _safeNotify();
    try {
      await _persistCurrentSessionId(local.sessionId);
    } catch (error, stackTrace) {
      debugPrint(
        '[Session] failed to persist local collaboration copy selection: '
        '$error\n$stackTrace',
      );
    }
    return local;
  }

  /// Replaces the current synchronized replica with one independent local
  /// Session. Rust changes the Session and Log IDs atomically so rejoining the
  /// server Session later cannot collide with the converted local record.
  Future<Session> convertCurrentCollaborationSessionToLocal() async {
    await ready;
    final sourceSessionId = _currentSessionId;
    if (sourceSessionId == null || _currentSession == null) {
      throw StateError('NO_CURRENT_SESSION');
    }

    final local = await _collaborationSessionLocalConverter(sourceSessionId);
    if (_currentSessionId != sourceSessionId) {
      throw StateError('SESSION_CONTEXT_CHANGED');
    }
    if (local.sessionId == sourceSessionId || local.status != 'active') {
      throw StateError('LOCAL_SESSION_CONVERSION_INVALID');
    }

    _currentSession = local;
    _currentSessionId = local.sessionId;
    _safeNotify();
    try {
      await _persistCurrentSessionId(local.sessionId);
    } catch (error, stackTrace) {
      debugPrint(
        '[Session] failed to persist converted local Session selection: '
        '$error\n$stackTrace',
      );
    }
    return local;
  }

  Future<void> reloadCurrentSession() async {
    final sessionId = _currentSessionId;
    if (sessionId == null) return;
    final sessions = await RustApi.listSessions();
    final matches = sessions.where((session) => session.sessionId == sessionId);
    if (matches.isEmpty) {
      await handleSessionDeleted(sessionId);
      _safeNotify();
      return;
    }
    _currentSession = matches.first;
    _safeNotify();
  }

  Future<void> renameCurrentSession(String title) async {
    final normalized = title.trim();
    if (normalized.isEmpty || normalized.length > 200) {
      throw ArgumentError('会话标题长度应为 1–200 个字符');
    }
    final sessionId = _currentSessionId;
    final session = _currentSession;
    if (sessionId == null || session == null) {
      throw StateError('NO_CURRENT_SESSION');
    }
    if (session.status != 'active') {
      throw StateError('SESSION_CLOSED');
    }
    if (normalized == session.title) return;

    await RustApi.updateCollaborationSessionTitle(
      sessionId: sessionId,
      title: normalized,
    );
    if (_currentSessionId == sessionId) {
      await reloadCurrentSession();
    }
  }

  Future<void> handleSessionDeleted(String sessionId) async {
    if (_currentSessionId == sessionId) {
      _currentSession = null;
      _currentSessionId = null;
      final prefs = await SharedPreferences.getInstance();
      await prefs.remove(_key);
    }
  }

  Future<void> _saveCurrentSessionId() async {
    if (_currentSessionId != null) {
      await _persistCurrentSessionId(_currentSessionId!);
    }
  }

  Future<void> _persistCurrentSessionId(String sessionId) async {
    final writer = _currentSessionIdWriter;
    final saved = writer != null
        ? await writer(sessionId)
        : await (await SharedPreferences.getInstance()).setString(
            _key,
            sessionId,
          );
    if (!saved) {
      throw StateError('Failed to persist current session: $sessionId');
    }
  }
}
