import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:openlogtool/database/database_helper.dart';
import 'package:openlogtool/models/session.dart';
import 'package:openlogtool/services/instance_service.dart';

class SessionProvider with ChangeNotifier {
  static const _key = 'current_session_id';

  bool _disposed = false;
  String? _currentSessionId;
  Session? _currentSession;
  Completer<void>? _initCompleter;

  String? get currentSessionId => _currentSessionId;
  Session? get currentSession => _currentSession;

  /// Resolves once initial bootstrap is done (the first valid session is
  /// loaded or created). Other code can await this to avoid races with a
  /// not-yet-initialized session.
  Future<void> get ready => _initCompleter?.future ?? Future.value();

  SessionProvider() {
    final completer = Completer<void>();
    _initCompleter = completer;
    scheduleMicrotask(() async {
      try {
        await _init();
      } catch (e, st) {
        debugPrint('[Session] init failed: $e\n$st');
      } finally {
        if (!completer.isCompleted) completer.complete();
      }
    });
  }

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  void _safeNotify() {
    if (_disposed) return;
    notifyListeners();
  }

  Future<void> _init() async {
    final prefs = await SharedPreferences.getInstance();
    final storedId = prefs.getString(_key);
    final db = DatabaseHelper();

    if (storedId != null && storedId.isNotEmpty) {
      // Validate that the stored session still exists AND is not deleted.
      final existing = await db.getSessionById(storedId);
      if (existing != null) {
        _currentSession = existing;
        _currentSessionId = existing.sessionId;
      } else {
        // Stale pointer – drop it so we don't write new logs into a ghost.
        debugPrint('[Session] stored session $storedId no longer exists, clearing');
        await prefs.remove(_key);
      }
    }

    if (_currentSession == null) {
      await _ensureActiveSession();
    }
    _safeNotify();
  }

  Future<void> _ensureActiveSession() async {
    final db = DatabaseHelper();
    final activeSessions = await db.getActiveSession();
    if (activeSessions.isNotEmpty) {
      _currentSession = Session.fromMap(activeSessions.first);
      _currentSessionId = _currentSession!.sessionId;
      await _saveCurrentSessionId();
      _safeNotify();
      return;
    }
    await startNewSession(autoGenerated: true);
  }

  Future<String> getOrCreateSessionId() async {
    await ready;
    if (_currentSessionId == null) {
      await _ensureActiveSession();
    }
    return _currentSessionId!;
  }

  Future<void> startNewSession(
      {String? title, bool autoGenerated = false}) async {
    final db = DatabaseHelper();

    try {
      if (_currentSessionId != null) {
        debugPrint('[Session] closing session: $_currentSessionId');
        await db.closeSession(_currentSessionId!);
      }

      final newSessionId = await Session.generateSessionId();
      final instanceId = await InstanceService.getInstanceId();
      final now = DateTime.now().toUtc();

      final defaultTitle = autoGenerated
          ? '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} ${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')} 记录'
          : ((title?.trim().isNotEmpty ?? false) ? title!.trim() : '新记录');

      final session = Session(
        sessionId: newSessionId,
        title: defaultTitle,
        status: 'active',
        createdAt: now.toIso8601String(),
        updatedAt: now.toIso8601String(),
        sourceDeviceId: instanceId,
      );

      debugPrint('[Session] inserting: ${session.toMap()}');
      await db.insertSession(session);
      _currentSessionId = newSessionId;
      _currentSession = session;
      await _saveCurrentSessionId();
      debugPrint('[Session] new session ready: $newSessionId');
      _safeNotify();
    } catch (e, st) {
      debugPrint('[Session] startNewSession ERROR: $e\n$st');
      rethrow;
    }
  }

  Future<void> switchToSession(String sessionId) async {
    final db = DatabaseHelper();
    final session = await db.getSessionById(sessionId);
    if (session == null) {
      debugPrint('[Session] switchToSession: $sessionId not found');
      return;
    }
    _currentSession = session;
    _currentSessionId = session.sessionId;
    await _saveCurrentSessionId();
    _safeNotify();
  }

  /// Called when a session is deleted externally — drops current pointer if
  /// it matches and falls back to ensure-or-create.
  Future<void> handleSessionDeleted(String sessionId) async {
    if (_currentSessionId == sessionId) {
      _currentSession = null;
      _currentSessionId = null;
      final prefs = await SharedPreferences.getInstance();
      await prefs.remove(_key);
      await _ensureActiveSession();
    }
  }

  Future<void> _saveCurrentSessionId() async {
    final prefs = await SharedPreferences.getInstance();
    if (_currentSessionId != null) {
      await prefs.setString(_key, _currentSessionId!);
    }
  }
}
