// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CallsignQthRecord {
  final PlatformInt64? id;
  final String syncId;
  final String callsign;
  final String qth;
  final String recordedAt;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;
  final String? sourceDeviceId;

  const CallsignQthRecord({
    this.id,
    required this.syncId,
    required this.callsign,
    required this.qth,
    required this.recordedAt,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    this.sourceDeviceId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      syncId.hashCode ^
      callsign.hashCode ^
      qth.hashCode ^
      recordedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallsignQthRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncId == other.syncId &&
          callsign == other.callsign &&
          qth == other.qth &&
          recordedAt == other.recordedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          sourceDeviceId == other.sourceDeviceId;
}
