// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DictItem {
  final PlatformInt64? id;
  final String dictType;
  final String raw;
  final String? pinyin;
  final String? abbreviation;
  final String syncId;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;

  const DictItem({
    this.id,
    required this.dictType,
    required this.raw,
    this.pinyin,
    this.abbreviation,
    required this.syncId,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      dictType.hashCode ^
      raw.hashCode ^
      pinyin.hashCode ^
      abbreviation.hashCode ^
      syncId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          dictType == other.dictType &&
          raw == other.raw &&
          pinyin == other.pinyin &&
          abbreviation == other.abbreviation &&
          syncId == other.syncId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}
