// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LogEntry {
  final PlatformInt64? id;
  final String syncId;
  final String sessionId;
  final String time;
  final String controller;
  final String callsign;
  final String? rstSent;
  final String? rstRcvd;
  final String? qth;
  final String? device;
  final String? power;
  final String? antenna;
  final String? height;
  final String? remarks;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;
  final String? sourceDeviceId;

  const LogEntry({
    this.id,
    required this.syncId,
    required this.sessionId,
    required this.time,
    required this.controller,
    required this.callsign,
    this.rstSent,
    this.rstRcvd,
    this.qth,
    this.device,
    this.power,
    this.antenna,
    this.height,
    this.remarks,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    this.sourceDeviceId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      syncId.hashCode ^
      sessionId.hashCode ^
      time.hashCode ^
      controller.hashCode ^
      callsign.hashCode ^
      rstSent.hashCode ^
      rstRcvd.hashCode ^
      qth.hashCode ^
      device.hashCode ^
      power.hashCode ^
      antenna.hashCode ^
      height.hashCode ^
      remarks.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      sourceDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncId == other.syncId &&
          sessionId == other.sessionId &&
          time == other.time &&
          controller == other.controller &&
          callsign == other.callsign &&
          rstSent == other.rstSent &&
          rstRcvd == other.rstRcvd &&
          qth == other.qth &&
          device == other.device &&
          power == other.power &&
          antenna == other.antenna &&
          height == other.height &&
          remarks == other.remarks &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          sourceDeviceId == other.sourceDeviceId;
}

class LogStats {
  final PlatformInt64 total;
  final PlatformInt64 today;
  final PlatformInt64 last7Days;

  const LogStats({
    required this.total,
    required this.today,
    required this.last7Days,
  });

  @override
  int get hashCode => total.hashCode ^ today.hashCode ^ last7Days.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogStats &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          today == other.today &&
          last7Days == other.last7Days;
}
