// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Session {
  final String sessionId;
  final String title;
  final String status;
  final String? shareCode;
  final String createdAt;
  final String updatedAt;
  final String? closedAt;
  final String? deletedAt;

  const Session({
    required this.sessionId,
    required this.title,
    required this.status,
    this.shareCode,
    required this.createdAt,
    required this.updatedAt,
    this.closedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      title.hashCode ^
      status.hashCode ^
      shareCode.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      closedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Session &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          title == other.title &&
          status == other.status &&
          shareCode == other.shareCode &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          closedAt == other.closedAt &&
          deletedAt == other.deletedAt;
}
